#pragma once

#include <concepts>
#include <iosfwd>
#include <iostream>
#include <string>
#include <string_view>

namespace template_method_pattern_modern::crtp {

template<typename Derived>
class ReportGenerator {
public:
    void generate(const std::string_view title, std::ostream& out) const
    {
        const auto& self = static_cast<const Derived&>(*this);

        if constexpr (requires { self.before_generate(out); }) {
            self.before_generate(out);
        }

        out << "# " << title << '\n';

        const auto raw_data = self.collect_data();
        out << self.format_body(raw_data) << '\n';

        if (should_include_footer(self)) {
            out << "-- generated by CRTP template method\n";
        }

        if constexpr (requires { self.after_generate(out); }) {
            self.after_generate(out);
        }
    }

private:
    static bool should_include_footer(const Derived& self)
    {
        if constexpr (requires { { self.include_footer() } -> std::convertible_to<bool>; }) {
            return self.include_footer();
        }

        return true;
    }
};

}  // namespace template_method_pattern_modern::crtp
