find_package(GTest CONFIG REQUIRED)

include(GoogleTest)

add_subdirectory(CommandPattern)
add_subdirectory(DecoratorPattern)
add_subdirectory(ObserverPattern)
add_subdirectory(SimpleFactoryPseudoPattern)
add_subdirectory(SingletonPattern)
add_subdirectory(StrategyPattern)
add_subdirectory(TemplateMethodPattern)
