#pragma once

#include <concepts>
#include <iosfwd>
#include <iostream>
#include <string>
#include <string_view>

namespace template_method_pattern_modern::deducing_this {

struct ReportGenerator {
    template<typename Self>
    // Explicit object parameter, also known as "deducing this", is a C++23 feature.
    void generate(this const Self& self, const std::string_view title, std::ostream& out)
    {
        if constexpr (requires { self.before_generate(out); }) {
            self.before_generate(out);
        }

        out << "# " << title << '\n';

        const auto raw_data = self.collect_data();
        out << self.format_body(raw_data) << '\n';

        if constexpr (requires { { self.include_footer() } -> std::convertible_to<bool>; }) {
            if (self.include_footer()) {
                out << "-- generated by deducing-this template method\n";
            }
        } else {
            out << "-- generated by deducing-this template method\n";
        }

        if constexpr (requires { self.after_generate(out); }) {
            self.after_generate(out);
        }
    }
};

}  // namespace template_method_pattern_modern::deducing_this
