#pragma once

#include <functional>
#include <ostream>
#include <string>
#include <string_view>

namespace template_method_pattern_modern::callable {

struct ReportSteps {
    std::function<std::string()> collect_data;
    std::function<std::string(std::string_view)> format_body;
    std::function<void(std::ostream&)> before_generate;
    std::function<bool()> include_footer;
    std::function<void(std::ostream&)> after_generate;
};

inline void generate_report(
    const ReportSteps& steps,
    std::string_view title,
    std::ostream& out)
{
    if (steps.before_generate) {
        steps.before_generate(out);
    }

    out << "# " << title << '\n';

    const auto raw_data = steps.collect_data();
    out << steps.format_body(raw_data) << '\n';

    const auto include_footer = steps.include_footer ? steps.include_footer() : true;
    if (include_footer) {
        out << "-- generated by callable template method\n";
    }

    if (steps.after_generate) {
        steps.after_generate(out);
    }
}

}  // namespace template_method_pattern_modern::callable
