#include <TemplateMethodPattern_modern/callable/CallableReportWorkflow.hpp>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <ostream>
#include <sstream>
#include <string>
#include <string_view>

namespace {

using testing::Eq;

constexpr auto kDefaultBody =
    "# Report\n"
    "Body from raw-data\n";

constexpr auto kHookedBody =
    "before\n"
    "# Report\n"
    "Body from raw-data\n"
    "after\n";

template_method_pattern_modern::callable::ReportSteps make_minimal_steps()
{
    return {
        .collect_data = [] {
            return std::string{"raw-data"};
        },
        .format_body = [](const std::string_view raw_data) {
            return std::string{"Body from "} + std::string{raw_data};
        },
    };
}

template_method_pattern_modern::callable::ReportSteps make_hooked_steps()
{
    auto steps = make_minimal_steps();
    steps.before_generate = [](std::ostream& out) {
        out << "before\n";
    };
    steps.include_footer = [] {
        return false;
    };
    steps.after_generate = [](std::ostream& out) {
        out << "after\n";
    };
    return steps;
}

TEST(CallableTemplateMethod, MinimalStepsUseDefaultFooter)
{
    std::ostringstream out;

    template_method_pattern_modern::callable::generate_report(
        make_minimal_steps(),
        "Report",
        out);

    EXPECT_THAT(out.str(), Eq(std::string{kDefaultBody}
        + "-- generated by callable template method\n"));
}

TEST(CallableTemplateMethod, HooksRunAroundReportAndCanSuppressFooter)
{
    std::ostringstream out;

    template_method_pattern_modern::callable::generate_report(
        make_hooked_steps(),
        "Report",
        out);

    EXPECT_THAT(out.str(), Eq(kHookedBody));
}

}  // namespace
