#include <TemplateMethodPattern_modern/crtp/CrtpReportGenerator.hpp>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <ostream>
#include <sstream>
#include <string>
#include <string_view>

namespace {

using testing::Eq;

constexpr auto kDefaultBody =
    "# Report\n"
    "Body from raw-data\n";

constexpr auto kHookedBody =
    "before\n"
    "# Report\n"
    "Body from raw-data\n"
    "after\n";

template<typename Derived>
using ReportGenerator = template_method_pattern_modern::crtp::ReportGenerator<Derived>;

struct MinimalReport : ReportGenerator<MinimalReport> {
    std::string collect_data() const
    {
        return "raw-data";
    }

    std::string format_body(const std::string_view raw_data) const
    {
        return std::string{"Body from "} + std::string{raw_data};
    }
};

struct HookedReport : ReportGenerator<HookedReport> {
    void before_generate(std::ostream& out) const
    {
        out << "before\n";
    }

    std::string collect_data() const
    {
        return "raw-data";
    }

    std::string format_body(const std::string_view raw_data) const
    {
        return std::string{"Body from "} + std::string{raw_data};
    }

    bool include_footer() const
    {
        return false;
    }

    void after_generate(std::ostream& out) const
    {
        out << "after\n";
    }
};

struct ExplicitFooterReport : ReportGenerator<ExplicitFooterReport> {
    void before_generate(std::ostream& out) const
    {
        out << "before\n";
    }

    std::string collect_data() const
    {
        return "raw-data";
    }

    std::string format_body(const std::string_view raw_data) const
    {
        return std::string{"Body from "} + std::string{raw_data};
    }

    bool include_footer() const
    {
        return true;
    }

    void after_generate(std::ostream& out) const
    {
        out << "after\n";
    }
};

TEST(CrtpTemplateMethod, MinimalReportUsesDefaultFooter)
{
    std::ostringstream out;
    const MinimalReport report;

    report.generate("Report", out);

    EXPECT_THAT(out.str(), Eq(std::string{kDefaultBody}
        + "-- generated by CRTP template method\n"));
}

TEST(CrtpTemplateMethod, HooksRunAroundReportAndCanSuppressFooter)
{
    std::ostringstream out;
    const HookedReport report;

    report.generate("Report", out);

    EXPECT_THAT(out.str(), Eq(kHookedBody));
}

TEST(CrtpTemplateMethod, ExplicitFooterCanKeepFooterBetweenHooks)
{
    std::ostringstream out;
    const ExplicitFooterReport report;

    report.generate("Report", out);

    EXPECT_THAT(out.str(), Eq(std::string{
        "before\n"
        "# Report\n"
        "Body from raw-data\n"
        "-- generated by CRTP template method\n"
        "after\n"}));
}

}  // namespace
