#include <TemplateMethodPattern_modern/concepts/ReportWorkflow.hpp>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <ostream>
#include <sstream>
#include <string>
#include <string_view>

namespace {

using testing::Eq;

constexpr auto kDefaultBody =
    "# Report\n"
    "Body from raw-data\n";

constexpr auto kHookedBody =
    "before\n"
    "# Report\n"
    "Body from raw-data\n"
    "after\n";

struct MinimalSteps {
    std::string collect_data() const
    {
        return "raw-data";
    }

    std::string format_body(const std::string_view raw_data) const
    {
        return std::string{"Body from "} + std::string{raw_data};
    }
};

struct HookedSteps : MinimalSteps {
    void before_generate(std::ostream& out) const
    {
        out << "before\n";
    }

    bool include_footer() const
    {
        return false;
    }

    void after_generate(std::ostream& out) const
    {
        out << "after\n";
    }
};

struct ExplicitFooterSteps : MinimalSteps {
    void before_generate(std::ostream& out) const
    {
        out << "before\n";
    }

    bool include_footer() const
    {
        return true;
    }

    void after_generate(std::ostream& out) const
    {
        out << "after\n";
    }
};

TEST(ConceptsTemplateMethod, MinimalStepsUseDefaultFooter)
{
    std::ostringstream out;

    template_method_pattern_modern::concepts_based::generate_report(
        MinimalSteps{},
        "Report",
        out);

    EXPECT_THAT(out.str(), Eq(std::string{kDefaultBody}
        + "-- generated by concepts template method\n"));
}

TEST(ConceptsTemplateMethod, HooksRunAroundReportAndCanSuppressFooter)
{
    std::ostringstream out;

    template_method_pattern_modern::concepts_based::generate_report(
        HookedSteps{},
        "Report",
        out);

    EXPECT_THAT(out.str(), Eq(kHookedBody));
}

TEST(ConceptsTemplateMethod, ExplicitFooterCanKeepFooterBetweenHooks)
{
    std::ostringstream out;

    template_method_pattern_modern::concepts_based::generate_report(
        ExplicitFooterSteps{},
        "Report",
        out);

    EXPECT_THAT(out.str(), Eq(
        "before\n"
        "# Report\n"
        "Body from raw-data\n"
        "-- generated by concepts template method\n"
        "after\n"));
}

}  // namespace
