#include <TemplateMethodPattern_modern/deducing_this/DeducingThisReportGenerator.hpp>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <ostream>
#include <sstream>
#include <string>
#include <string_view>

namespace {

using testing::Eq;

constexpr auto kDefaultBody =
    "# Report\n"
    "Body from raw-data\n";

constexpr auto kHookedBody =
    "before\n"
    "# Report\n"
    "Body from raw-data\n"
    "after\n";

using ReportGenerator = template_method_pattern_modern::deducing_this::ReportGenerator;

struct MinimalReport : ReportGenerator {
    std::string collect_data() const
    {
        return "raw-data";
    }

    std::string format_body(const std::string_view raw_data) const
    {
        return std::string{"Body from "} + std::string{raw_data};
    }
};

struct HookedReport : MinimalReport {
    void before_generate(std::ostream& out) const
    {
        out << "before\n";
    }

    bool include_footer() const
    {
        return false;
    }

    void after_generate(std::ostream& out) const
    {
        out << "after\n";
    }
};

TEST(DeducingThisTemplateMethod, MinimalReportUsesDefaultFooter)
{
    std::ostringstream out;
    const MinimalReport report;

    report.generate("Report", out);

    EXPECT_THAT(out.str(), Eq(std::string{kDefaultBody}
        + "-- generated by deducing-this template method\n"));
}

TEST(DeducingThisTemplateMethod, HooksRunAroundReportAndCanSuppressFooter)
{
    std::ostringstream out;
    const HookedReport report;

    report.generate("Report", out);

    EXPECT_THAT(out.str(), Eq(kHookedBody));
}

}  // namespace
