#include <TemplateMethodPattern_classic/AuditReportGenerator.hpp>
#include <TemplateMethodPattern_classic/SalesReportGenerator.hpp>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <sstream>

namespace {

using testing::Eq;

using template_method_pattern_classic::AuditReportGenerator;
using template_method_pattern_classic::SalesReportGenerator;

TEST(ClassicTemplateMethod, SalesReportUsesDefaultWorkflowWithFooter)
{
    std::ostringstream out;
    const SalesReportGenerator generator{out};

    generator.generate("Monthly sales");

    EXPECT_THAT(out.str(), Eq(
        "# Monthly sales\n"
        "Sales report from orders=42;revenue=1200\n"
        "-- generated by classic template method\n"));
}

TEST(ClassicTemplateMethod, AuditReportRunsHooksAndOmitsFooter)
{
    std::ostringstream out;
    const AuditReportGenerator generator{out};

    generator.generate("Security audit");

    EXPECT_THAT(out.str(), Eq(
        "Opening audit trail\n"
        "# Security audit\n"
        "Audit report from login=ok;permissions=reviewed\n"
        "Closing audit trail\n"));
}

}  // namespace
