#include <TemplateMethodPattern_classic/ReportGenerator.hpp>

#include <iostream>

namespace template_method_pattern_classic {

ReportGenerator::ReportGenerator(std::ostream& out)
    : out_{out}
{
}

void ReportGenerator::generate(const std::string_view title) const
{
    before_generate();

    out_ << "# " << title << '\n';
    const auto raw_data = collect_data();
    out_ << format_body(raw_data) << '\n';

    if (include_footer()) {
        out_ << "-- generated by classic template method\n";
    }

    after_generate();
}

void ReportGenerator::before_generate() const
{
    // do nothing by default
}

bool ReportGenerator::include_footer() const
{
    return true;
}

void ReportGenerator::after_generate() const
{
    // do nothing by default
}

std::ostream& ReportGenerator::out() const
{
    return out_;
}

}  // namespace template_method_pattern_classic
