#pragma once

#include <concepts>
#include <iosfwd>
#include <iostream>
#include <string>
#include <string_view>

namespace template_method_pattern_modern::concepts_based {

template<typename Steps>
concept ReportSteps = requires(const Steps steps, std::string_view raw_data) {
    { steps.collect_data() } -> std::convertible_to<std::string>;
    { steps.format_body(raw_data) } -> std::convertible_to<std::string>;
};

template<ReportSteps Steps>
void generate_report(const Steps& steps, const std::string_view title, std::ostream& out)
{
    if constexpr (requires { steps.before_generate(out); }) {
        steps.before_generate(out);
    }

    out << "# " << title << '\n';

    const auto raw_data = steps.collect_data();
    out << steps.format_body(raw_data) << '\n';

    if constexpr (requires { { steps.include_footer() } -> std::convertible_to<bool>; }) {
        if (steps.include_footer()) {
            out << "-- generated by concepts template method\n";
        }
    } else {
        out << "-- generated by concepts template method\n";
    }

    if constexpr (requires { steps.after_generate(out); }) {
        steps.after_generate(out);
    }
}

}  // namespace template_method_pattern_modern::concepts_based
